import os
import django
import random

# Set up Django environment
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'project.settings')
django.setup()

from app.models import PlaceMode

# List of Maharashtra tourist places with details
maharashtra_places = [
    {
        "Name": "Mahabaleshwar",
        "City": "Mahabaleshwar",
        "Zone": "Western Maharashtra",
        "Type": "hill station",
        "State": "Maharashtra",
        "Description": "Mahabaleshwar is a hill station located in the Western Ghats, in Satara district of Maharashtra. Apart from its strawberries, Mahabaleshwar is also well known for its numerous rivers, magnificent cascades and majestic peaks. It is among the most sought after weekend getaways from Pune & Mumbai.",
        "Year": "Ancient",
        "Time_needed": "2-3 days",
        "Google_rating": "4.1",
        "Significance": "Natural Beauty",
        "Best_time_to_visit": "October to June",
        "Fees": "Free",
        "Image_url": "https://images.unsplash.com/photo-1625904835711-5d42fd02a177?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
    },
    {
        "Name": "Ajanta and Ellora Caves",
        "City": "Aurangabad",
        "Zone": "Marathwada",
        "Type": "heritage",
        "State": "Maharashtra",
        "Description": "Ajanta and Ellora caves, considered to be one of the finest examples of ancient rock-cut caves, are located near Aurangabad in Maharashtra, India. Ajanta and Ellora caves complex is adorned with beautiful sculptures, paintings, and frescoes and include Buddhist monasteries, Hindu and Jain temples. The Ajanta caves are 29 in number and were built between the 2nd century BCE and 6th century CE, while the Ellora caves are 34 in number and were built between the 6th and 11th century CE.",
        "Year": "2nd century BCE",
        "Time_needed": "1-2 days",
        "Google_rating": "4.7",
        "Significance": "Historical",
        "Best_time_to_visit": "June to March",
        "Fees": "₹40 for Indians, ₹600 for foreigners",
        "Image_url": "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
    },
    {
        "Name": "Panchgani",
        "City": "Panchgani",
        "Zone": "Western Maharashtra",
        "Type": "hill station",
        "State": "Maharashtra",
        "Description": "Deriving its name from the five hills surrounding it, Panchgani is a popular hill station near Mahabaleshwar in Maharashtra, famous for its various sunset and sunrise points and scenic valley view. The Table Land, a vast volcanic plateau that forms the second-highest mountain plateau in Asia, is the main attraction here.",
        "Year": "1860s",
        "Time_needed": "1-2 days",
        "Google_rating": "4.6",
        "Significance": "Natural Beauty",
        "Best_time_to_visit": "September to May",
        "Fees": "Free",
        "Image_url": "https://images.unsplash.com/photo-1625904835711-5d42fd02a177?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
    },
    {
        "Name": "Lavasa",
        "City": "Lavasa",
        "Zone": "Western Maharashtra",
        "Type": "hill station",
        "State": "Maharashtra",
        "Description": "Known as India's newest hill station, the Lavasa Corporation is constructing this private city. The city is a beautiful project, stylistically based on the Italian town Portofino. Spreading across 7 hills, covering an area of 25000 acres, Lavasa is a perfect blend of beauty and infrastructure.",
        "Year": "2000s",
        "Time_needed": "1-2 days",
        "Google_rating": "4.7",
        "Significance": "Modern Architecture",
        "Best_time_to_visit": "Throughout the year",
        "Fees": "Free",
        "Image_url": "https://images.unsplash.com/photo-1625904835711-5d42fd02a177?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
    },
    {
        "Name": "Shirdi",
        "City": "Shirdi",
        "Zone": "Northern Maharashtra",
        "Type": "pilgrimage",
        "State": "Maharashtra",
        "Description": "Located at a distance of 122 Km from Nasik in the Ahmednagar district of Maharashtra, Shirdi is the home of Sai Baba. It is believed that Sai Baba arrived at Shirdi in 1858 and spent 60 years of his life here until he attained salvation in 1918. Sai Baba is popularly known as the 'child of God', as his parentage and origins are still unknown.",
        "Year": "1858",
        "Time_needed": "1 day",
        "Google_rating": "4.5",
        "Significance": "Religious",
        "Best_time_to_visit": "July to March",
        "Fees": "Free",
        "Image_url": "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
    },
    {
        "Name": "Kolad",
        "City": "Kolad",
        "Zone": "Konkan",
        "Type": "adventure",
        "State": "Maharashtra",
        "Description": "Famous for white water rafting, Kolad is a thriving tiny village in the Raigad district in Maharashtra. Known for its cascading waterfalls, green meadows and picturesque backdrop of Sahyadris, Kolad is gaining traction as an adventure sports destination with provisions for rafting, rappelling, and kayaking.",
        "Year": "Modern",
        "Time_needed": "1-2 days",
        "Google_rating": "4.0",
        "Significance": "Adventure",
        "Best_time_to_visit": "June to March",
        "Fees": "Varies by activity",
        "Image_url": "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
    },
    {
        "Name": "Bhandardara",
        "City": "Bhandardara",
        "Zone": "Western Maharashtra",
        "Type": "hill station",
        "State": "Maharashtra",
        "Description": "Bhandardara, a hill station nestled in the Sahyadri ranges of Maharashtra, has all the nature's blessings a place can get. The lush greenery, the humble waterfalls and surrounded by high mountains makes for the perfect holiday spot for city dwellers.",
        "Year": "Ancient",
        "Time_needed": "1-2 days",
        "Google_rating": "4.8",
        "Significance": "Natural Beauty",
        "Best_time_to_visit": "June to March",
        "Fees": "Free",
        "Image_url": "https://images.unsplash.com/photo-1625904835711-5d42fd02a177?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
    },
    {
        "Name": "Rajmachi",
        "City": "Lonavala",
        "Zone": "Western Maharashtra",
        "Type": "heritage",
        "State": "Maharashtra",
        "Description": "Rajmachi is a small village situated in the Sahyadri mountain range of the Konkan region of Maharashtra. Rajmachi is famous for the historical fortress which has two fortified peaks - Shrivardhan and Manaranjan forts, located near two famous hills of Lonavala and Khandala.",
        "Year": "17th century",
        "Time_needed": "1 day",
        "Google_rating": "4.6",
        "Significance": "Historical",
        "Best_time_to_visit": "June to September",
        "Fees": "Free",
        "Image_url": "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
    },
    {
        "Name": "Lonavala",
        "City": "Lonavala",
        "Zone": "Western Maharashtra",
        "Type": "hill station",
        "State": "Maharashtra",
        "Description": "Situated in the Sahyadri range of the Western Ghats close to Pune and Mumbai, Lonavala is the most visited hill station in Maharashtra and the place to be during monsoons. With lots of waterfalls, lakes and hills around, it is a popular destination for camping, trekking and other adventure sports.",
        "Year": "Ancient",
        "Time_needed": "2-3 days",
        "Google_rating": "4.4",
        "Significance": "Natural Beauty",
        "Best_time_to_visit": "Throughout the year",
        "Fees": "Free",
        "Image_url": "https://images.unsplash.com/photo-1625904835711-5d42fd02a177?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
    },
    {
        "Name": "Alibaug",
        "City": "Alibaug",
        "Zone": "Konkan",
        "Type": "beach",
        "State": "Maharashtra",
        "Description": "Alibaug (also spelled as Alibag) is a small coastal town in the Konkan region of Maharashtra, known for its beaches, villas, and beautiful scenery. Alibag is very popular as a weekend getaway from the cities of Mumbai and Pune.",
        "Year": "17th century",
        "Time_needed": "2-3 days",
        "Google_rating": "4.5",
        "Significance": "Beaches",
        "Best_time_to_visit": "November to March",
        "Fees": "Free",
        "Image_url": "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
    },
    {
        "Name": "Khandala",
        "City": "Khandala",
        "Zone": "Western Maharashtra",
        "Type": "hill station",
        "State": "Maharashtra",
        "Description": "Khandala is a popular hill station in Maharashtra, perched on the foothills of Sahyadri in the Western Ghats. Khandala provides for a perfect weekend respite for the Mumbai population, with its scenic valleys, grassy hills, serene lakes and misty waterfalls.",
        "Year": "Ancient",
        "Time_needed": "1-2 days",
        "Google_rating": "4.6",
        "Significance": "Natural Beauty",
        "Best_time_to_visit": "Throughout the year",
        "Fees": "Free",
        "Image_url": "https://images.unsplash.com/photo-1625904835711-5d42fd02a177?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
    },
    {
        "Name": "Tarkarli",
        "City": "Tarkarli",
        "Zone": "Konkan",
        "Type": "beach",
        "State": "Maharashtra",
        "Description": "Tarkarli is famous for its long and narrow stretch of beach, with its pristine water, white sand, and of course Singhudurg, Maharashtra's popular sea fort. It's also known for water sports and the Karli backwaters.",
        "Year": "Ancient",
        "Time_needed": "2-3 days",
        "Google_rating": "4.1",
        "Significance": "Beaches",
        "Best_time_to_visit": "October to March",
        "Fees": "Free",
        "Image_url": "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
    },
    {
        "Name": "Kashid",
        "City": "Kashid",
        "Zone": "Konkan",
        "Type": "beach",
        "State": "Maharashtra",
        "Description": "A Beach town, popular for its white sand and blue seas situated in Konkan region of Maharashtra, Kashid is the perfect destination for a quiet weekend getaway from Mumbai.",
        "Year": "Ancient",
        "Time_needed": "1-2 days",
        "Google_rating": "4.3",
        "Significance": "Beaches",
        "Best_time_to_visit": "October to March",
        "Fees": "Free",
        "Image_url": "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
    },
    {
        "Name": "Nashik",
        "City": "Nashik",
        "Zone": "Northern Maharashtra",
        "Type": "pilgrimage",
        "State": "Maharashtra",
        "Description": "Nasik is a religious Hindu city, host to the Kumbh Mela every 12 years. It also makes for a perfect wine tasting destination. Nashik (Nasik), named after a relic associated with Ramayana, is a city in Maharashtra located on the banks of river Godavari.",
        "Year": "Ancient",
        "Time_needed": "2-3 days",
        "Google_rating": "4.3",
        "Significance": "Religious",
        "Best_time_to_visit": "July to March",
        "Fees": "Free",
        "Image_url": "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
    },
    {
        "Name": "Aurangabad",
        "City": "Aurangabad",
        "Zone": "Marathwada",
        "Type": "heritage",
        "State": "Maharashtra",
        "Description": "Aurangabad, which was declared by the Government as the Tourism Capital of Maharashtra back in 2010, is a famous tourist hub which greets its visitors with a richly woven tapestry of sights and sounds. The city got its name for being the erstwhile capital of Mughal Emperor Aurangzeb in the 17th century.",
        "Year": "17th century",
        "Time_needed": "2-3 days",
        "Google_rating": "4.3",
        "Significance": "Historical",
        "Best_time_to_visit": "October to March",
        "Fees": "Free",
        "Image_url": "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
    },
    {
        "Name": "Ganpatipule",
        "City": "Ganpatipule",
        "Zone": "Konkan",
        "Type": "beach",
        "State": "Maharashtra",
        "Description": "Beach town on the Konkan coastline, Ganpatipule has temples of Lord Ganesha as major attractions apart from the beautiful virgin beaches.",
        "Year": "Ancient",
        "Time_needed": "1-2 days",
        "Google_rating": "4.2",
        "Significance": "Religious",
        "Best_time_to_visit": "November to February",
        "Fees": "Free",
        "Image_url": "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
    },
    {
        "Name": "Matheran",
        "City": "Matheran",
        "Zone": "Western Maharashtra",
        "Type": "hill station",
        "State": "Maharashtra",
        "Description": "Nestled amidst the Sahyadri range on the Western Ghats, Matheran is a cosy little hill station that stands at an elevation of 2600 feet above sea level, and is just 100 kilometres away from Mumbai, making it the perfect weekend getaway. With its name literally translating to 'overhead forest', Matheran is the smallest hill station in India but is extremely popular in the state of Maharashtra.",
        "Year": "1850",
        "Time_needed": "2-3 days",
        "Google_rating": "4.1",
        "Significance": "Natural Beauty",
        "Best_time_to_visit": "Throughout the year",
        "Fees": "Free",
        "Image_url": "https://images.unsplash.com/photo-1625904835711-5d42fd02a177?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
    },
    {
        "Name": "Raigad",
        "City": "Raigad",
        "Zone": "Konkan",
        "Type": "heritage",
        "State": "Maharashtra",
        "Description": "Raigad, is a historically rich district is situated in the Konkan region of Maharashtra. Located at 2,851mts, it is surrounded by Mumbai Harbour, Thane, Pune, Ratnagiri and the Arabian Sea.",
        "Year": "17th century",
        "Time_needed": "1-2 days",
        "Google_rating": "4.2",
        "Significance": "Historical",
        "Best_time_to_visit": "November to March",
        "Fees": "Free",
        "Image_url": "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
    },
    {
        "Name": "Amboli",
        "City": "Amboli",
        "Zone": "Konkan",
        "Type": "hill station",
        "State": "Maharashtra",
        "Description": "Amboli lies in the Sahyadri hills in the Sindhudurg district of Maharashtra. It is the last hill station of Maharashtra before the plains of Goa begin and is a relatively unexplored one.",
        "Year": "Ancient",
        "Time_needed": "1-2 days",
        "Google_rating": "4.6",
        "Significance": "Natural Beauty",
        "Best_time_to_visit": "June to September",
        "Fees": "Free",
        "Image_url": "https://images.unsplash.com/photo-1625904835711-5d42fd02a177?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
    },
    {
        "Name": "Tadoba National Park",
        "City": "Chandrapur",
        "Zone": "Vidarbha",
        "Type": "wildlife",
        "State": "Maharashtra",
        "Description": "Famous for its natural heritage, Tadoba Andhari Tiger Reserve is definitely one of India's most exciting and best protected Tiger Reserve, with most visible tiger sightings in the state of Maharashtra.",
        "Year": "1955",
        "Time_needed": "2-3 days",
        "Google_rating": "4.4",
        "Significance": "Wildlife",
        "Best_time_to_visit": "October to March",
        "Fees": "₹200 for Indians, ₹1500 for foreigners",
        "Image_url": "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
    },
    {
        "Name": "Kamshet",
        "City": "Kamshet",
        "Zone": "Western Maharashtra",
        "Type": "adventure",
        "State": "Maharashtra",
        "Description": "Kamshet is a picturesque hill station in Western Ghats, renowned for paragliding and flying schools. Surrounded by Western Ghats, this place is regularly featured in the top 10 must visit destinations of India for an adventurous junkie.",
        "Year": "Modern",
        "Time_needed": "1-2 days",
        "Google_rating": "4.4",
        "Significance": "Adventure",
        "Best_time_to_visit": "October to June",
        "Fees": "Varies by activity",
        "Image_url": "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
    },
    {
        "Name": "Durshet",
        "City": "Durshet",
        "Zone": "Konkan",
        "Type": "adventure",
        "State": "Maharashtra",
        "Description": "Durshet is a little village found on the banks of the river Amba, nestled in the Sahyadri ranges of Maharashtra. Due to its proximity to Mumbai and Pune it serves as a weekend getaway for people to move away from the crowded cities.",
        "Year": "Ancient",
        "Time_needed": "1-2 days",
        "Google_rating": "4.2",
        "Significance": "Adventure",
        "Best_time_to_visit": "September to February",
        "Fees": "Free",
        "Image_url": "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
    },
    {
        "Name": "Bhimashankar",
        "City": "Bhimashankar",
        "Zone": "Western Maharashtra",
        "Type": "pilgrimage",
        "State": "Maharashtra",
        "Description": "Bhimashankar, located about 100 km from Pune and 223 km from Mumbai, is a popular temple town. It is among one of the twelve traditional 'Jyotilingam' shrines of Lord Shiva in India.",
        "Year": "Ancient",
        "Time_needed": "1 day",
        "Google_rating": "4.7",
        "Significance": "Religious",
        "Best_time_to_visit": "November to February",
        "Fees": "Free",
        "Image_url": "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
    },
    {
        "Name": "Malvan",
        "City": "Malvan",
        "Zone": "Konkan",
        "Type": "beach",
        "State": "Maharashtra",
        "Description": "Malvan is a culturally and historically important town in the Sindhudurg district of Maharashtra. It is well known historically for the Sindhudurg Fort of Chatrapati Shivajiraje. Culturally, it is famous for it's mouth-watering Malvani sea-food and sweets. Malvan is also known for its beaches that are relatively less crowded compared to other popular beaches in the state.",
        "Year": "17th century",
        "Time_needed": "2-3 days",
        "Google_rating": "4.1",
        "Significance": "Beaches",
        "Best_time_to_visit": "November to March",
        "Fees": "Free",
        "Image_url": "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
    },
    {
        "Name": "Kolhapur",
        "City": "Kolhapur",
        "Zone": "Western Maharashtra",
        "Type": "heritage",
        "State": "Maharashtra",
        "Description": "Kolhapur is situated on the banks of the river Panchaganga in the south-west region of Maharashtra. Situated 230 kilometres away from Pune, Kolhapur is one of the princely states and boasts of a rich legacy dating back to the times of the Marathas. Presently, Kolhapur is known for Kolhapuri chappals, Kolhapuri cuisine, and the Mahalaxmi Temple.",
        "Year": "Ancient",
        "Time_needed": "2-3 days",
        "Google_rating": "4.2",
        "Significance": "Historical",
        "Best_time_to_visit": "July to February",
        "Fees": "Free",
        "Image_url": "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
    },
    {
        "Name": "Karjat",
        "City": "Karjat",
        "Zone": "Western Maharashtra",
        "Type": "adventure",
        "State": "Maharashtra",
        "Description": "Karjat, a quaint little village is the last station of Thane district in Maharashtra. The river Ulhas finds its origin in Karjat and trekking and historical spots make it a popular destination for trekkers and adventure enthusiasts.",
        "Year": "Ancient",
        "Time_needed": "1-2 days",
        "Google_rating": "4.5",
        "Significance": "Adventure",
        "Best_time_to_visit": "June to September",
        "Fees": "Free",
        "Image_url": "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
    },
    {
        "Name": "Igatpuri",
        "City": "Igatpuri",
        "Zone": "Northern Maharashtra",
        "Type": "hill station",
        "State": "Maharashtra",
        "Description": "Igatpuri is a hill station and a city in the Western Ghats located in the Nashik district of Maharashtra, 130kms from Mumbai. Located on the Mumbai-Agra National Highway, Igatpuri is a heaven for nature lovers. It also has some of the highest peaks of the Sahyadri range.",
        "Year": "Ancient",
        "Time_needed": "1-2 days",
        "Google_rating": "4.2",
        "Significance": "Natural Beauty",
        "Best_time_to_visit": "July to September",
        "Fees": "Free",
        "Image_url": "https://images.unsplash.com/photo-1625904835711-5d42fd02a177?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
    },
    {
        "Name": "Diveagar",
        "City": "Diveagar",
        "Zone": "Konkan",
        "Type": "beach",
        "State": "Maharashtra",
        "Description": "Gleaming white sand, pristine blue water, swaying coconut palms and betel nut trees and gentle breeze producing a serene and calming effect, this is not a dream but the enchanting place called Diveagar.",
        "Year": "Ancient",
        "Time_needed": "1-2 days",
        "Google_rating": "4.7",
        "Significance": "Beaches",
        "Best_time_to_visit": "October to March",
        "Fees": "Free",
        "Image_url": "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
    },
    {
        "Name": "Suryamal",
        "City": "Suryamal",
        "Zone": "Western Maharashtra",
        "Type": "adventure",
        "State": "Maharashtra",
        "Description": "Suryamal is the highest peak of the region, located in Thane district of Maharashtra. The small but beautiful hill is a popular place among people for the sheer breathtaking views that it can be seen from the hilltop.",
        "Year": "Ancient",
        "Time_needed": "1 day",
        "Google_rating": "4.5",
        "Significance": "Adventure",
        "Best_time_to_visit": "September to May",
        "Fees": "Free",
        "Image_url": "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
    },
    {
        "Name": "Harihareshwar",
        "City": "Harihareshwar",
        "Zone": "Konkan",
        "Type": "beach",
        "State": "Maharashtra",
        "Description": "Surrounded by four hills and with river Savitri flowing through the town, Harihareshwar is famous for its temple of Lord Harihareshwar and is a popular weekend beach destination especially for people in Mumbai and Pune.",
        "Year": "Ancient",
        "Time_needed": "1-2 days",
        "Google_rating": "4.7",
        "Significance": "Religious",
        "Best_time_to_visit": "October to March",
        "Fees": "Free",
        "Image_url": "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
    },
    {
        "Name": "Ratanwadi",
        "City": "Ratanwadi",
        "Zone": "Western Maharashtra",
        "Type": "heritage",
        "State": "Maharashtra",
        "Description": "Ratanwadi is a village near Bhandardara of the Kalsubai peak in Maharashtra. It houses the famous Ratangad fort and the popular Shiva temple called Amruteshwar. It is a famous trekking spot as it is far from the main town and has a rustic charm to it.",
        "Year": "Ancient",
        "Time_needed": "1 day",
        "Google_rating": "4.3",
        "Significance": "Historical",
        "Best_time_to_visit": "September to May",
        "Fees": "Free",
        "Image_url": "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
    },
    {
        "Name": "Manori",
        "City": "Mumbai",
        "Zone": "Konkan",
        "Type": "beach",
        "State": "Maharashtra",
        "Description": "Manori beach, along with Gorai beach is a growing favourite among back packers and people who just want to cross over to the peace and quiet of the country side for a while.",
        "Year": "Ancient",
        "Time_needed": "1 day",
        "Google_rating": "4.0",
        "Significance": "Beaches",
        "Best_time_to_visit": "Throughout the year",
        "Fees": "Free",
        "Image_url": "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
    },
    {
        "Name": "Chiplun",
        "City": "Chiplun",
        "Zone": "Konkan",
        "Type": "heritage",
        "State": "Maharashtra",
        "Description": "In the quiet, far away from the city port district of Ratnagiri in Maharashtra, lies Chiplun, the city that offers you time among mango groves next to the beautiful lake, Vashishti. This town is most known for its white sand beaches and beautiful mango and cashew groves by the Vashishti river.",
        "Year": "Ancient",
        "Time_needed": "1-2 days",
        "Google_rating": "4.0",
        "Significance": "Natural Beauty",
        "Best_time_to_visit": "July to February",
        "Fees": "Free",
        "Image_url": "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
    },
    {
        "Name": "Chikhaldara",
        "City": "Chikhaldara",
        "Zone": "Vidarbha",
        "Type": "hill station",
        "State": "Maharashtra",
        "Description": "The scent of coffee enchants you as you enter the hill station city of Chikhaldara in the state of Maharashtra. Being the only coffee growing area in the region, Chikhaldara also boasts of beautiful lakes, breathtaking panoramic viewpoints and exotic wildlife.",
        "Year": "Ancient",
        "Time_needed": "2-3 days",
        "Google_rating": "4.8",
        "Significance": "Natural Beauty",
        "Best_time_to_visit": "July to February",
        "Fees": "Free",
        "Image_url": "https://images.unsplash.com/photo-1625904835711-5d42fd02a177?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
    },
    {
        "Name": "Ratnagiri",
        "City": "Ratnagiri",
        "Zone": "Konkan",
        "Type": "beach",
        "State": "Maharashtra",
        "Description": "Situated in pretty surroundings, Ratnagiri is blessed with hills, sea shores, creeks, beautiful rivers, hot water springs, forests and water falls and offers a rejuvenating experience to travelers.",
        "Year": "Ancient",
        "Time_needed": "2-3 days",
        "Google_rating": "4.3",
        "Significance": "Beaches",
        "Best_time_to_visit": "October to March",
        "Fees": "Free",
        "Image_url": "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
    },
    {
        "Name": "Panvel",
        "City": "Panvel",
        "Zone": "Konkan",
        "Type": "heritage",
        "State": "Maharashtra",
        "Description": "Best known as the gateway of Konkan coast, Panvel is the most crowded locality of Raigad District of Maharashtra. Located at a distance of 40kms from Mumbai metropolitan region, Panvel is highly populated. It is known for the forts in Raigad and Khopoli; and also the Karnala fort which is a popular trekking destination.",
        "Year": "Ancient",
        "Time_needed": "1-2 days",
        "Google_rating": "4.3",
        "Significance": "Historical",
        "Best_time_to_visit": "July to February",
        "Fees": "Free",
        "Image_url": "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
    },
    {
        "Name": "Murud Janjira",
        "City": "Murud",
        "Zone": "Konkan",
        "Type": "beach",
        "State": "Maharashtra",
        "Description": "Murud is known for it widespread sandy beaches adorned with majestic forts and outlined by palms and coconut trees, creating a perfect holiday scenery.",
        "Year": "17th century",
        "Time_needed": "1-2 days",
        "Google_rating": "4.5",
        "Significance": "Beaches",
        "Best_time_to_visit": "Throughout the year",
        "Fees": "Free",
        "Image_url": "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
    },
    {
        "Name": "Dapoli",
        "City": "Dapoli",
        "Zone": "Konkan",
        "Type": "hill station",
        "State": "Maharashtra",
        "Description": "Dapoli, situated 215km away from Mumbai is popular tourist destination that serves the needs of all kinds of travelers. It is known as mini-Mahabaleshwar of Maharashtra owing to its cool climate throughout the year. It is located in the Ratnagiri district and is a famous Konkan hill station.",
        "Year": "Ancient",
        "Time_needed": "2-3 days",
        "Google_rating": "4.7",
        "Significance": "Natural Beauty",
        "Best_time_to_visit": "June to September",
        "Fees": "Free",
        "Image_url": "https://images.unsplash.com/photo-1625904835711-5d42fd02a177?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
    },
    {
        "Name": "Malshej Ghat",
        "City": "Malshej Ghat",
        "Zone": "Western Maharashtra",
        "Type": "hill station",
        "State": "Maharashtra",
        "Description": "Malshej Ghat is a mountain pass and a popular hill station, nestled in the Western Ghats of Maharashtra. With its numerous lakes, waterfalls, mountains, and verdant flora and fauna, Malshej Ghat is popular among hikers, trekkers and nature lovers.",
        "Year": "Ancient",
        "Time_needed": "1-2 days",
        "Google_rating": "4.8",
        "Significance": "Natural Beauty",
        "Best_time_to_visit": "July to March",
        "Fees": "Free",
        "Image_url": "https://images.unsplash.com/photo-1625904835711-5d42fd02a177?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
    },
    {
        "Name": "Elephanta Caves",
        "City": "Mumbai",
        "Zone": "Konkan",
        "Type": "heritage",
        "State": "Maharashtra",
        "Description": "The Elephanta Caves are a UNESCO World Heritage Site and a collection of cave temples predominantly dedicated to the Hindu god Shiva. They are located on Elephanta Island, or Gharapuri in Mumbai Harbour, 10 kilometers to the east of the city of Mumbai.",
        "Year": "5th to 8th century",
        "Time_needed": "1 day",
        "Google_rating": "4.5",
        "Significance": "Historical",
        "Best_time_to_visit": "November to February",
        "Fees": "₹40 for Indians, ₹600 for foreigners",
        "Image_url": "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
    },
    {
        "Name": "Karnala Bird Sanctuary",
        "City": "Panvel",
        "Zone": "Konkan",
        "Type": "wildlife",
        "State": "Maharashtra",
        "Description": "Karnala Bird Sanctuary is a sanctuary located in Raigad district of Maharashtra, India. It is a popular destination for bird watchers and hikers, as it is home to over 150 species of resident and 37 species of migratory birds who visit the sanctuary during winter.",
        "Year": "1968",
        "Time_needed": "1 day",
        "Google_rating": "4.2",
        "Significance": "Wildlife",
        "Best_time_to_visit": "October to April",
        "Fees": "₹35 for Indians, ₹400 for foreigners",
        "Image_url": "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
    },
    {
        "Name": "Panhala Fort",
        "City": "Kolhapur",
        "Zone": "Western Maharashtra",
        "Type": "heritage",
        "State": "Maharashtra",
        "Description": "Panhala Fort, also known as Panhalgad, is located in Panhala, 20 kilometres northwest of Kolhapur in Maharashtra, India. It is strategically located looking over a pass in the Sahyadri mountain range which was a major trade route from Bijapur in the interior of Maharashtra to the coastal areas.",
        "Year": "1178",
        "Time_needed": "1 day",
        "Google_rating": "4.5",
        "Significance": "Historical",
        "Best_time_to_visit": "July to February",
        "Fees": "₹25 for Indians, ₹500 for foreigners",
        "Image_url": "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
    },
    {
        "Name": "Sinhagad Fort",
        "City": "Pune",
        "Zone": "Western Maharashtra",
        "Type": "heritage",
        "State": "Maharashtra",
        "Description": "Sinhagad is a fortress located roughly 30 kilometres southwest of the city of Pune, India. Previously called Kondhana, the fort has been the site of many important battles, most notably the Battle of Sinhagad in 1670. It was also strategically located at the centre of a string of other forts such as Rajgad, Purandar and Torna.",
        "Year": "1643",
        "Time_needed": "1 day",
        "Google_rating": "4.6",
        "Significance": "Historical",
        "Best_time_to_visit": "June to February",
        "Fees": "₹50",
        "Image_url": "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
    },
    {
        "Name": "Pratapgad Fort",
        "City": "Satara",
        "Zone": "Western Maharashtra",
        "Type": "heritage",
        "State": "Maharashtra",
        "Description": "Pratapgad is a mountain fort located in Satara district, in the Western Indian state of Maharashtra. The fort is situated 24 kilometres from the Mahabaleshwar hill station. The fort stands at an elevation of 1,080 metres above sea level and is built on a spur which overlooks the road to Mahabaleshwar.",
        "Year": "1656",
        "Time_needed": "1 day",
        "Google_rating": "4.6",
        "Significance": "Historical",
        "Best_time_to_visit": "October to June",
        "Fees": "₹20",
        "Image_url": "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
    },
    {
        "Name": "Shaniwar Wada",
        "City": "Pune",
        "Zone": "Western Maharashtra",
        "Type": "heritage",
        "State": "Maharashtra",
        "Description": "Shaniwar Wada is a historical fortification in the city of Pune in Maharashtra, India. Built in 1732, it was the seat of the Peshwas of the Maratha Empire until 1818, when the Peshwas lost control to the East India Company after the Third Anglo-Maratha War.",
        "Year": "1732",
        "Time_needed": "1 day",
        "Google_rating": "4.4",
        "Significance": "Historical",
        "Best_time_to_visit": "October to March",
        "Fees": "₹25 for Indians, ₹500 for foreigners",
        "Image_url": "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
    },
    {
        "Name": "Aga Khan Palace",
        "City": "Pune",
        "Zone": "Western Maharashtra",
        "Type": "heritage",
        "State": "Maharashtra",
        "Description": "The Aga Khan Palace was built by Sultan Muhammed Shah Aga Khan III in Pune, India. The palace was an act of charity by the Sultan who wanted to help the poor in the neighbouring areas of Pune, who were drastically hit by famine. The palace is closely linked to the Indian freedom movement as it served as a prison for Mahatma Gandhi, his wife Kasturba Gandhi, his secretary Mahadev Desai and Sarojini Naidu.",
        "Year": "1892",
        "Time_needed": "1 day",
        "Google_rating": "4.5",
        "Significance": "Historical",
        "Best_time_to_visit": "October to March",
        "Fees": "₹25 for Indians, ₹300 for foreigners",
        "Image_url": "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
    },
    {
        "Name": "Kaas Plateau",
        "City": "Satara",
        "Zone": "Western Maharashtra",
        "Type": "heritage",
        "State": "Maharashtra",
        "Description": "Kaas Plateau is a plateau situated 25 kilometres west from Satara city in Maharashtra, India. It falls under the Sahyadri Sub Cluster of the Western Ghats, and it became a part of a UNESCO World Natural Heritage Site in 2012. It is known for its wildflowers which bloom during the monsoon season, typically between August and October.",
        "Year": "Ancient",
        "Time_needed": "1 day",
        "Google_rating": "4.5",
        "Significance": "Natural Beauty",
        "Best_time_to_visit": "August to October",
        "Fees": "₹100 for Indians, ₹200 for foreigners",
        "Image_url": "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
    },
    {
        "Name": "Rajgad Fort",
        "City": "Pune",
        "Zone": "Western Maharashtra",
        "Type": "heritage",
        "State": "Maharashtra",
        "Description": "Rajgad is a hill fort situated in the Pune district of Maharashtra, India. Formerly known as Murumdev, it was renamed as Rajgad by Shivaji Maharaj. The fort was the capital of the Maratha Empire for almost 26 years, before the capital was moved to Raigad Fort.",
        "Year": "1646",
        "Time_needed": "1 day",
        "Google_rating": "4.7",
        "Significance": "Historical",
        "Best_time_to_visit": "June to February",
        "Fees": "Free",
        "Image_url": "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
    },
    {
        "Name": "Torna Fort",
        "City": "Pune",
        "Zone": "Western Maharashtra",
        "Type": "heritage",
        "State": "Maharashtra",
        "Description": "Torna Fort, also known as Prachandagad, is a large fort located in Pune district, in the Indian state of Maharashtra. It is historically significant because it was the first fort captured by Shivaji Maharaj in 1646, at the age of 16. The fort is situated at an elevation of 1,403 metres above sea level, making it the highest hill-fort in the district.",
        "Year": "1646",
        "Time_needed": "1 day",
        "Google_rating": "4.6",
        "Significance": "Historical",
        "Best_time_to_visit": "June to February",
        "Fees": "Free",
        "Image_url": "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
    },
    {
        "Name": "Lohagad Fort",
        "City": "Lonavala",
        "Zone": "Western Maharashtra",
        "Type": "heritage",
        "State": "Maharashtra",
        "Description": "Lohagad is one of the many hill forts of Maharashtra state in India. Situated close to the hill station Lonavala and 52 km northwest of Pune, Lohagad rises to an elevation of 1,033 m above sea level. The fort is connected to the neighboring Visapur fort by a small range.",
        "Year": "1564",
        "Time_needed": "1 day",
        "Google_rating": "4.6",
        "Significance": "Historical",
        "Best_time_to_visit": "June to February",
        "Fees": "₹25",
        "Image_url": "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
    },
]

# Check if places already exist in the database to avoid duplicates
existing_places = set(PlaceMode.objects.values_list('Name', flat=True))
added_count = 0
skipped_count = 0

# Add places to the database
for place in maharashtra_places:
    if place["Name"] not in existing_places:
        # Create a new place
        new_place = PlaceMode(
            place_id=random.randint(1000, 9999),  # Generate a random place_id
            Name=place["Name"],
            City=place["City"],
            Zone=place["Zone"],
            Type=place["Type"],
            State=place["State"],
            Description=place["Description"],
            Year=place["Year"],
            Time_needed=place["Time_needed"],
            Google_rating=place["Google_rating"],
            Significance=place["Significance"],
            Best_time_to_visit=place["Best_time_to_visit"],
            Fees=place["Fees"],
            Image_url=place["Image_url"],
        )
        new_place.save()
        added_count += 1
        print(f"Added: {place['Name']}")
    else:
        skipped_count += 1
        print(f"Skipped (already exists): {place['Name']}")

print(f"\nSummary: Added {added_count} new places, skipped {skipped_count} existing places.")
print("All Maharashtra tourist places have been added to the database successfully!")